### GET request to example server
GET http://localhost:8080/api/v1/projects

###
POST http://localhost:8080/api/v1/projects
Content-Type: application/json

{
  "name": "AI Productivity Platform",
  "description": "A platform to optimize developer workflow using AI agents.",
  "deadline": "2025-08-30",
  "status": "IN_PROGRESS"
}

###
PUT http://localhost:8080/api/v1/projects/2
Content-Type: application/json

{
        "title": "Workflow Platform",
        "description": "A platform to optimize developer workflow using AI agents.",
        "deadline": "2026-07-03T13:51:04.22",
        "status": "COMPLETED"
}

###
POST http://localhost:8080/api/v1/developers
Content-Type: application/json

{
    "developerName": "Kwame Mensah",
    "developerEmail": "kwame.mensah@buildmaster.com",
    "developerSkills": [
        "Java",
        "PostgreSQL",
        "Spring Boot"
    ]
}